#!/bin/bash

cat << EOF > ui_index.c
// This file was generated by ui_index.gen.sh, do not edit it manually
#include "ui_index.h"

ui_obj_map ui_objects[] = {
$(grep $'^[\t]*lv_obj_t \*' kvmui/gui_guider.h | sed 's/lv_obj_t \*//g' | sed 's/;//g' | while read -r line; do
    echo "    {\"$line\", &guider_ui.$line},"
done)
};

const int ui_objects_size = sizeof(ui_objects) / sizeof(ui_objects[0]);

EOF

echo "ui_index.c has been generated successfully."
